version: "3.9"

services:
  client:
    container_name: front-prod
    image: front-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
      - mynetwork
    ports:
      - '8080:81'
    stdin_open: true
    command:
      npm start

networks:
  mynetwork:
    external:
      name: mynetwork