version: "3.9"

services:
  client:
    container_name: front-dev
    image: front-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    stdin_open: true
    command:
      npm start